### ISSUE TITLE
cs:~omnivector/redis seems to be unavailable

### ISSUE THREAD

**Issue by ChrisMacNaughton** [omnivector-solutions/layer-redis#13]
When navigating to this charm page via the charmstore, it results in a 5xx error; when trying to deploy the charm via the CLI, "ERROR cannot resolve charm URL "cs:~omnivector/redis": cannot get "/~omnivector/redis/meta/any?include=id&include=supported-series&include=published": access denied for user ..."

**Comment by jamesbeedy** [comment]
@ChrisMacNaughton it looks like the read acls were revoked somehow. I've gone ahead and granted read to "everyone", it should be available now. 

```bash
$ charm show cs:~omnivector/redis
Persistent key-value database with network interface

Name			redis
Owner			omnivector
Revision		27
Supported Series	xenial, bionic
Tags			cache, db, redis
Subordinate		false
Promulgated		false
Home page		https://github.com/omnivector-solutions/layer-redis
Bugs url		https://github.com/omnivector-solutions/layer-redis/issues
Read			omnivector, everyone
Write			omnivector
 			 
CHANNEL			CURRENT
stable			true		
```
Thanks!
